name: Master release

on:
  push:
    branches:
      - master-release

jobs:
  master-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run test

      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git config --global pull.ff only

      - run: |
          set -euo pipefail
          # Make sure the remote branch exists or bootstrap it
          TMP="$(mktemp -d)"
          cp -r .git "$TMP/"
          cd "$TMP"
          git fetch
          git switch -c master-release-dist
          git branch --set-upstream-to=origin/master-release-dist master-release-dist && { exit 0; }
          git add .
          git commit -m "First empty commit"
          git push --set-upstream origin master-release-dist

      - uses: actions/checkout@v4
        with:
          ref: master-release-dist
          path: master-release-dist
      - run: |
          set -euo pipefail

          wdir="$(pwd)"
          branchDir="${GITHUB_WORKSPACE}/master-release-dist"

          cp "${wdir}/index.js" "${branchDir}/"
          cp -r "${wdir}/lib" "${branchDir}/"
          cp "${wdir}/package.json" "${branchDir}/"
          cp "${wdir}/package-lock.json" "${branchDir}/"

          cd "${branchDir}"
          git add .
          git commit -m "release-${GITHUB_SHA}" --allow-empty
          git push
          git tag "release-${GITHUB_SHA}"
          git push --tags

          echo "Released: release-${GITHUB_SHA}"

      - uses: ncipollo/release-action@v1
        with:
          tag: release-${{ github.sha }}
